### ISSUE TITLE
Set up a hostname under *.redhat.com for the product registry

### ISSUE THREAD

**Issue by johnmcollier** [redhat-developer/devfile-registry#3]
We're unable to use the existing devfile.io hostname for the Red Hat product devfile registry, and prefer to use something under redhat.com instead. This issue will track the work to request a subdomain under *.redhat.com for the registry

@elsony @slemeur any concerns with devfie-registry.redhat.com and devfile-registry.stage.redhat.com?

**Comment by elsony** [comment]
> @elsony @slemeur any concerns with devfie-registry.redhat.com and devfile-registry.stage.redhat.com?

Looks fine to me

**Comment by johnmcollier** [comment]
I requested the subdomain `devfile-registry.redhat.com`, waiting to hear back before proceeding.

**Comment by johnmcollier** [comment]
This can be closed out. devfile-registry.redhat.com has been created.
