### ISSUE TITLE
Link to CONTRIBUTING.md file in readme is invalid

### ISSUE THREAD

**Issue by marekkopecky** [redhat-developer/devfile-registry#6]
Link to CONTRIBUTING.md file in readme is invalid, it links to https://github.com/redhat-developer/devfile-registry/blob/main/CONTRIBUTING.md which returns 404

**Comment by johnmcollier** [comment]
I'll get one created.

**Comment by johnmcollier** [comment]
Fixed in https://github.com/redhat-developer/devfile-registry/pull/8

@marekkopecky sorry for the delay.
